### ISSUE TITLE
Preparación del proyecto

### ISSUE THREAD

**Issue by josopu96** [TFG-Veterinaria/VeterinApp#12]

**Comment by javirogo** [comment]
_Adjunto respuesta de trello en este hilo_

He cambiado el estilo de planificación en trello.
Traducido tanto las tareas de trello como las de toggle a Inglés.
Serán necesarios 5 Sprints de dos semanas cada uno, dejando una semana final para terminar posibles tareas atrasadas.
He dividido la historia de usuario 9 en tres historias de usuario más cortas.
Encontrada información sobre cómo elaborar el documento final de proyecto.
Creado documento de preguntas en google drive.
