### ISSUE TITLE
Planificación de las historias de usuario y las funcionalidades de la aplicación

### ISSUE THREAD

**Issue by josopu96** [TFG-Veterinaria/VeterinApp#2]

**Comment by javirogo** [comment]
Se ha reestructurado la planificación de acuerdo a la reunión del día 14 de Marzo.

Hemos decidido que las nuevas tareas que surjan a lo largo de los sprints se incluyan sin tiempo de estimación, ya que es algo que no estaba previsto desde un principio.

Hemos hecho la excepción con la investigación de base de datos. La cuál hemos incluido en la planificación del sprint 1.
