### ISSUE TITLE
HU 11 Editar perfil de usuario

### ISSUE THREAD

**Issue by josopu96** [TFG-Veterinaria/VeterinApp#29]

**Comment by javirogo** [comment]
Te comento lo que me falla, para que lo mires luego.
El botón de permisos de administrador me sale siempre marcado, independientemente de si es administrador o no.
Si no es administrador, aunque salga marcado, si guardas no se queda como administrador, hay que desmarcarlo y volver a marcarlo.
La antigua contraseña, da igual lo que pongas, parece que no comprueba que coincida con la contraseña actual (le cambiaría el título a contraseña actual, aunque eso no lo he considerado fallo xD).
Si la nueva contraseña no coincide en su repetición, no muestra ningún mensaje (es lo que hemos dicho hace un momento), hay que tenerlo en cuenta tb.
