### ISSUE TITLE
Revisión del sprint 1

### ISSUE THREAD

**Issue by josopu96** [TFG-Veterinaria/VeterinApp#34]

**Comment by javirogo** [comment]
Desarrollo:
- Validación de las acciones de la reunión anterior.
- Se propone el uso del proyecto base disponible en https://github.com/maximegris/angular-electron como punto de partida para la aplicación.

Por parte de los alumnos:
- Desarrollo del layout de la UI, e integración del login y la conexión con la BD usando el proyecto plantilla mencionado arriba.
- Comenzar con el caso de uso de login simple.
- Angular tour of heroes.
- Hacerlo para familiarizarse con la tecnología.
- Desarrollar los componentes de las ventanas principales.
- Ojo con el Router!!!.
