### ISSUE TITLE
HU 16 Historial de mascotas

### ISSUE THREAD

**Issue by josopu96** [TFG-Veterinaria/VeterinApp#39]

**Comment by josopu96** [comment]
![Ver mascota](https://user-images.githubusercontent.com/18394300/59452055-310a7a00-8e0d-11e9-910a-fd49e6ac136d.png)

**Comment by josopu96** [comment]
@josopu96 Mirar la historia de usuario 16 para la tabla de la derecha

**Comment by javirogo** [comment]
Terminado!!!
