### ISSUE TITLE
Mock-ups

### ISSUE THREAD

**Issue by josopu96** [TFG-Veterinaria/VeterinApp#5]

**Comment by javirogo** [comment]
## Resumen de lo que falta por incluir en los mockups

Apartado de operaciones:
- Asignar tratamientos
- Asignar pruebas
- Imprimir recetas
- Gestión de tipos de pruebas, tipos de tratamiento, tarifas y productos.
- Crear facturas de tratamientos y de productos.

Incluir el envío de SMS en alguna parte.

Apartado datos de la aplicación:
- Gestión de los veterinarios (está ya hecho, pero quedaría enlazarlo desde ahí).
- Gestión de los usuarios.
- Datos de la clínica.

Calendario (hay un calendario autogenerado muy fácil de usar del que podemos ir tirando).
- Crear visitas en el calendario.

Ajustes:
- Tema, tamaño de letra y recordatorios (es sólo un mock-up en teoría).

Al finalizar todo, hacer guía de pasos a recorrer para visualizar la aplicación.

**Comment by javirogo** [comment]
## Actualización de lo que falta por incluir en los mockups

#### Apartado de operaciones:
- Asignar tratamientos
- Imprimir recetas

#### Apartado de datos de la aplicación:
- Gestión de tipos de pruebas, tipos de tratamiento, tarifas y productos.

Incluir el **envío de SMS** en alguna parte (se podría hacer automáticamente con los recordatorios y las citas a clientes que tengan el móvil registrado. En ese caso hay que añadir la posibilidad de quitar recordatorios al cliente si lo pide).

Al finalizar todo, **hacer guía de pasos** a recorrer para visualizar la aplicación.

**Comment by javirogo** [comment]
## Guía de pasos a seguir en los mockups.

- Página de inicio.
- Lista de clientes.
- Filtras por morosos.
- Quitas filtro.
- Seleccionas a Javier Rodríguez.
- Seleccionas a Jose Daniel.
- Limpias selección.
- Nuevo cliente.
- Agregar método de contacto.
- Aceptar formulario.
- Rellenar formulario (click en nombre)
- Guardar (se selecciona el cliente automáticamente).
- Ver cliente.
- Editar cliente.
- Volver hasta la lista de clientes.
- Limpias selección de cliente.
- Lista de mascotas.
- Nueva mascota (salta mensaje de advertencia).
- Selecciona la opción elegir cliente.
- Eliges de cliente a Alberto Jimenez.
- Vuelves a la lista de mascotas.
- Quitas filtro automático.
- Vuelves a poner filtro.
- Nueva mascota.
- Rellenas datos de la mascota (click en nombre).
- Guardar (se selecciona la mascota automáticamente).
- Ver mascota (click en cuadro de arriba o en la vista de la tabla).
- Navegas en los 7 menús de la mascota.
- Seleccionar veterinario (click en el menú de arriba).
- Seleccionar a Angel Ristori.
- Ver veterinario.
- Cerrar vista de veterinario.
- Abrimos el calendario.
- Click en el 28 de Marzo (simula el click derecho del raton).
- Nueva cita para cliente.
- Aceptar.
- Click en el 28 de Marzo de nuevo (simula el click derecho del raton).
- Nueva cita para mascota.
- Aceptar.
- Click en el 26 de Marzo.
- Cerrar ventana.
- Operaciones.
- Nuevo tratamiento.
- Click en Anamnesis para rellenar datos.
- Click en generar receta (la marcamos).
- Click en generar receta (la desmarcamos).
- Guardamos el tratamiento.
- Imprimimos la receta.
- Elegimos que sí, a generar receta.
- Volvemos a operaciones.
- Vacuna.
- Click en vacuna para rellenar datos.
- Guardamos la vacuna.
- Volvemos a operaciones.
- Desparasitación.
- Click en desparasitación para rellenar datos.
- Guardamos la desparasitación.
- Volvemos a operaciones.
- Nueva prueba.
- Desplegar la selección de tipos de prueba.
- Seleccionar prueba de insulina en ayunas.
- Click en categoría para rellenar datos.
- Click en fecha de radiografías para rellenar datos.
- Click en elegir archivo.
- Seleccionar la foto.
- Click en subir foto.
- Guardamos.
- Volvemos a operaciones.
- Analítica.
- Click en nombre para rellenar datos.
- Guardamos.
- Volvemos a operaciones.
- Radiografía.
- Elegir archivo.
- Elegimos la segunda foto.
- Pulsamos en subir foto.
- Seleccionamos enlazar a prueba.
- Seleccionamos la prueba.
- Guardar.
- Vamos a la sección de pruebas de la mascota (ahora tiene 2 radiografías).
- Vamos a la sección resumen de la mascota.
- Ahora se muestra el nuevo tratamiento, la nueva analítica y la nueva prueba (las radiografías asociadas a pruebas no se muestran).
- Volvemos a operaciones.
- Factura.
- Seleccionamos dos unidades de meloxicam.
- Añadimos al carrito.
- Seleccionamos una unidad de Hepatosil.
- Añadimos al carrito.
- Seleccionamos asociar tratamiento a la factura.
- Visualizamos el tratamiento.
- Volvemos a la vista de la factura.
- Seleccionamos el tratamiento.
- Pulsamos en precio para rellenar datos.
- Añadimos tratamiento.
- Desplegamos los tipos de pago.
- Seleccionamos tarjeta.
- Marcamos como pagado.
- Guardamos.
- Seleccionamos NO imprimir ahora.
- Limpiar selección de mascota.
- Limpiar selección de cliente.
- Limpiar selección de veterinario.
- Datos de la aplicación.
- Veterinarios (ya mostrado anteriormente).
- Volvemos a datos de la aplicación.
- Usuarios.
- Editar a rgallego.
- Eliminar usuario.
- Aceptamos la advertencia y lo eliminamos.
- Volvemos a datos de la aplicación.
- Clínica.
- Editamos los datos.
- Click en CIF para rellenar datos.
- Guardar.
- Volvemos a datos de la aplicación.
- Gestión.
- Tipos de tratamientos.
- Volver a la gestión.
- Tipos de pruebas.
- Volver a la gestión.
- Tarifas.
- Volver a la gestión.
- Productos.
- Vemos el primer producto.
- Volvemos a la lista.
- Editamos el primer producto.
- Cancelamos para volver a la lista.
- Añadir stock al primer producto.
- Cancelamos para volver a la lista.
- Volver a la gestión.
- Ahora abrimos los ajustes de la aplicación desde el menú de arriba.
- Elegimos el tema oscuro.
- Elegimos el tema claro.
- Cerramos sesión.
