### ISSUE TITLE
Modelo de dominio

### ISSUE THREAD

**Issue by josopu96** [TFG-Veterinaria/VeterinApp#6]

**Comment by javirogo** [comment]
Se ha completado el modelo de dominio. Las clases utilizadas serán las siguiente:
- Usuario.
- Ajustes.
- Clínica.
- Veterinario.
- Producto.
- Stock.
- ItemFactura.
- Factura.
- Tarifa.
- Tratamiento.
- TipoTratamiento.
- Receta.
- Mascota.
- Pelo.
- Capa.
- Especie.
- Raza.
- Prueba.
- TipoPrueba.
- Radiografía.
- Analítica.
- Cuidado.
- Cliente.
- Contacto.
- Visita.
- Calendario.

Se han definido todos sus atributos y se ha especificado la relación entre cada una de las clases nombradas anteriormente.
